return {
	["Chest"] = {
		Description = "Small chest that can store up to 16 items at once",
		Icon = "116351272851196",
		Type = "Chest",
		Rarity = "Common",
		Stacking = false
	},
	["Ender Chest"] = {
		Description = "Magic chest that can be accessed from anywhere without losing the stored items",
		Icon = "116961636636828",
		Type = "Chest",
		Rarity = "Epic",
		Stacking = false
	},
	
	["WorkBench"] = {
		Description = "A workbench that can be used to craft useful items",
		Icon = "95597729124168",
		Type = "Block",
		Rarity = "Common",
		Stacking = true,
		placeable = true
	},
	
	["Bow"] = {
		Description = "A tool used to shoot at objects in game.\nRequires arrows.",
		Icon = "116077391812048",
		Type = "Weapon",
		Rarity = "Common",
		Stacking = false
	},
	
	["IronHelmet"] = {
		Description = "Extra Protection!\nLimited Durability.",
		Icon = "378591491",
		Type = "Armor",
		Rarity = "Rare",
		Stacking = false
	},
	
	["Rainbow Potion"] = {
		Description = "idk wat this is...",
		Icon = "",
		Type = "Potion",
		Rarity = "Legendary",
		Stacking = false,
		consumable = true,
	},
}